server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://zone:8080/eureka
spring:
  application:
    name: security-server

#分布式事务
tx-lcn:
  client:
    manager-address: zone:8070
  # 是否启动LCN负载均衡策略(优化选项，开启与否，功能不受影响)
  ribbon:
    loadbalancer:
      dtx.enabled: true
  springcloud:
    loadbalance:
      enabled: true
