server:
  port: 7970
eureka:
  client:
    service-url:
      defaultZone: http://zone:8080/eureka
  instance:
    appname: txm-server

spring:
  application:
    name: txm-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://111.229.49.130:3306/frog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      validation-query: select 1 from dual
      initial-size: 1
      max-active: 20
      max-wait: 1000
      filters: stat
      pool-prepared-statements: false
      test-on-borrow: true
      test-while-idle: true
  #引入JPA，方便导入tx-lcn相关依赖表
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 1
    host: 111.229.49.130
    port: 6379

#tm配置
tx-lcn:
  logger:
    driver-class-name: ${spring.datasource.druid.driver-class-name}
    enabled: true
    jdbc-url: ${spring.datasource.druid.url}
    password: ${spring.datasource.druid.password}
    username: ${spring.datasource.druid.username}
  manager:
    admin-key: root
    concurrent-level: 128
    dtx-lock-time: ${tx-lcn.manager.dtx-time}
    dtx-time: 30000
    ex-url-enabled: false
    heart-time: 15000
    host: zone
    port: 8070
    seq-len: 12
  message:
    netty:
      attr-delay-time: 10000

logging:
  level:
    com:
      codingapi: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true