spring:
  application:
    name: message-server
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://zone:8080/eureka
sms:
  # 验证码长度
  length: 4
  # 验证码有效期（秒）
  time: 300
  aliyun:
    SignName: 柚子抢单
    TemplateCode: SMS_172884873

jpush:
  credit:
    masterSecret: 42eac727223bbb45a85092d2
    appKey: e471bb0eeb30d85093663955

aliyun:
  id: LTAISA6Zaiv6F3oU
  secret: iIay5XZ3LQDNK7lTVcxDfxJHVpo31s
  oss:
    AccessKey-ID:  LTAI4FwX5gBbLKKub1cY8XZ6
    AccessKey-Secret: t0LzBuPg1p13rTw4M6YWWb7Qs5AU4o
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    bucket-name: fs-server1
    file-url: https://fs-server1.oss-cn-shenzhen.aliyuncs.com/

smsChinese:
  uid: 71钱包
  key: d41d8cd98f00b204e980